# codemagic.yaml (Corrected Version for Unsigned/Local-Signed Build)

workflows:
  macos-build-local-sign:
    name: macOS Build (Local Sign)
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.yourcompany.yourappname" 
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: 'stable'
      xcode: 'latest'
      cocoapods: 'default'

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Flutter build for macOS
        script: |
          # 现在直接运行构建命令即可
          # Xcode 会根据我们项目中的 "Sign to Run Locally" 设置来正确执行
          flutter build macos --release

    artifacts:
      - build/macos/Build/Products/Release/*.app